### ISSUE TITLE
Topic Data structure fix

### ISSUE THREAD

**Issue by ajtoussaint** [Lockwood-02/Paista#32]
Based on our documentation topics should have the following attributes: 
- ID (Primary Key): auto-increment integer
- Description: VARCHAR(N)
- Title: VARCHAR(N)
- Private: Boolean
- Closed: Boolean
- Date_Created: Timestamp
- Deleted: Boolean

The sequelize.js file for topic does not have all of these and we will need some of them to implement other features. If you work on this you will also need to look at all of the routes that deal with topics to make sure they don't break with the change. Possibly the front end as well.

**Comment by Mkayuni** [comment]
I believe I fixed the issue now. Let me know if there is anything else with the changes.
